In [5]:
import numpy as np
import pandas as pd

import pandas as pd

from statsmodels.discrete import discrete_model
import statsmodels.formula.api as smf
from statsmodels.discrete.discrete_model import Poisson as psn,NegativeBinomial as ngb,MNLogit


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from numpy import random

import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t

import pylab
from pylab import legend, plot, show ,title, xlabel, ylabel

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from statsmodels.stats.outliers_influence import variance_inflation_factor

from statsmodels.stats import proportion as ssp

from scipy.stats import chisquare, chi2_contingency

from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix,classification_report

from statsmodels import discrete
from statsmodels.discrete import discrete_model
from statsmodels.discrete.discrete_model import MNLogit

from statsmodels.miscmodels.ordinal_model import OrderedModel

from sklearn.preprocessing import MinMaxScaler,StandardScaler

from sklearn.feature_selection import mutual_info_classif,SelectKBest

from sklearn.ensemble import ExtraTreesClassifier

from sklearn.feature_selection import SequentialFeatureSelector

from sklearn.linear_model import LinearRegression

from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import GaussianNB

In [6]:
df=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='iris')

In [7]:
x=df.drop('Species',axis=1)
y=df.Species


In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [9]:
mod3= GaussianNB().fit(x_train,y_train)

In [10]:
y_pred=mod3.predict(x_test)
print(confusion_matrix(y_test,y_pred))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  2  9]]


In [11]:
print(classification_report(y_test,y_pred))


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.85      1.00      0.92        11
 Iris-virginica       1.00      0.82      0.90        11

       accuracy                           0.93        30
      macro avg       0.95      0.94      0.94        30
   weighted avg       0.94      0.93      0.93        30

