# PCA and LDA
- Used for dimensionality reduction
- 

# PCA-
- unsupervised learning algorithm.
- PCA is used for marked and unmarked dataa
- in general, 2-3 dimensions can explain 80 percent of the variation in our data.


# LDA- Linear 
- supervised learning algorithm


-**PCA and LDA require scaling**

In [41]:
import numpy as np
import pandas as pd

import pandas as pd

from statsmodels.discrete import discrete_model
import statsmodels.formula.api as smf
from statsmodels.discrete.discrete_model import Poisson as psn,NegativeBinomial as ngb,MNLogit


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from numpy import random

import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t

import pylab
from pylab import legend, plot, show ,title, xlabel, ylabel

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from statsmodels.stats.outliers_influence import variance_inflation_factor

from statsmodels.stats import proportion as ssp

from scipy.stats import chisquare, chi2_contingency

from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix,classification_report

from statsmodels import discrete
from statsmodels.discrete import discrete_model
from statsmodels.discrete.discrete_model import MNLogit

from statsmodels.miscmodels.ordinal_model import OrderedModel

from sklearn.preprocessing import MinMaxScaler,StandardScaler

from sklearn.feature_selection import mutual_info_classif,SelectKBest

from sklearn.ensemble import ExtraTreesClassifier

from sklearn.feature_selection import SequentialFeatureSelector

from sklearn.linear_model import LinearRegression

from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [19]:
df=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='iris')

In [20]:
x=df.drop('Species',axis=1)
y=df.Species

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=20)

In [34]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [35]:
# scaling can be avoiding in xgbboost,gradboost,random forest ,etc 
# It is preferred in other models pca,lda,kmeans,hierachical clustering scaling is necessary
# Can be used in linear regresession

In [36]:
pc_mod=PCA(n_components=2)   #2 OuT OF 4 COMPONENTS will be taken
x_train=pc_mod.fit_transform(x_train)
x_test=pc_mod.transform(x_test)

In [37]:
exp_var=pc_mod.explained_variance_ratio_
exp_var  #hence using pca which condenses the model to just 2 axes(2 features), can explain 96%(0.72+0.23=0.96 approx) of variation in the data

array([0.72756536, 0.23418645])

In [38]:
# usING DTREE-

mod1= DecisionTreeClassifier(max_depth=3)
mod1.fit(x_train,y_train)
y_pred=mod1.predict(x_test)

In [39]:
print(confusion_matrix(y_test,y_pred))

[[12  0  0]
 [ 0 11  3]
 [ 0  3  9]]


In [40]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.79      0.79      0.79        14
 Iris-virginica       0.75      0.75      0.75        12

       accuracy                           0.84        38
      macro avg       0.85      0.85      0.85        38
   weighted avg       0.84      0.84      0.84        38



- Each principal component which has been extracted is a linear combination of multiple variables.
- These 2 variables are **not** 2 individual variables out of 4 but a combination of variables of all the features.
- For example if salary has features like age, experience,etc then new variables var 1 and var2 which will be a combination of all the 
original variables

# LDA

#Assumptions-
- The input dataset has a gaussian or normal distribution.
- The dataset is linearly seperable(can draw a line or plane to seperate the datapoints).

#Considerations-

The axes are chosen in such a way-
- that the difference between means(avg) of different classes are maximized.
- that the variance within a class should be minimized

In [51]:
df=pd.read_excel('CDAC_DataBook.xlsx',sheet_name='iris')

In [52]:
x=df.drop('Species',axis=1)
y=df.Species

In [53]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=20)

In [54]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [55]:
lda_mod=LinearDiscriminantAnalysis()
x_train=lda_mod.fit_transform(x_train,y_train)
x_test=lda_mod.transform(x_test)

In [56]:
mod2=DecisionTreeClassifier(max_depth=3)
mod2.fit(x_train,y_train)
y_pred=mod2.predict(x_test)

In [57]:
print(confusion_matrix(y_test,y_pred))

[[12  0  0]
 [ 0 14  0]
 [ 0  1 11]]


In [58]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.93      1.00      0.97        14
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        38
      macro avg       0.98      0.97      0.97        38
   weighted avg       0.98      0.97      0.97        38



The new axes we prepare are called eigenvectors. The importance of the axes is determined by eigen values. 

The n-best axes are determined by eigen values. The n-best with highest eigen values are chosen.



vector value   %age<br>
e1      17.3    .41<br>
e2      8.5        <br> 
e3      9.8     .23<br>
e4      6.2


Total =41.8


if n=2 then- e1 and e3 are chosen and can explain about .64 of the variation in the dataset.

The direction of the axes are determined by the best eigen vectors, their magnitude by eigen values.


In [60]:
a=np.array([4,6,5,7,8])
b=np.array([3,4,2,6,9])

In [62]:
np.cov(a,b)

array([[2.5, 4. ],
       [4. , 7.7]])

**Covarience matrix will always be a square matrix**


In [64]:
np.var(a,ddof=1)

np.float64(2.5)

In [65]:
np.var(b,ddof=1)


np.float64(7.7)

**Covarience matrix will always be a square matrix**
